### ISSUE TITLE
License for tutorial code

### ISSUE THREAD

**Issue by gdgib-roche** [teambit/bit-angular-tutorial#3]
Hey everyone!

Looking through this, I noticed there's no license associated with the tutorial code.  I would guess that's because you meant for it to be free for anyone to use, but [here's what happens when you don't choose a license](https://choosealicense.com/no-permission/).  If you want something more permissive than [Apache 2](https://github.com/teambit/bit/blob/prod/LICENSE) may I suggest [choosealicense](https://choosealicense.com/) as a place to start, and perhaps [the unlicense](https://choosealicense.com/licenses/unlicense/) specifically.  I've found that helpful for tutorial/example code that I intend for others to copy freely into their projects.

**Comment by itaymendel** [comment]
Hi, sorry about that. As you can see in our codebases, generally we use either MIT or Apache2 on our OSS code. In this case, perhaps we have forgotten to attach the MIT license file.
I'm adding it to this repo.

**Comment by gdgib-roche** [comment]
I figured, but better safe than sorry.  Thank you!
